#!/usr/bin/env python3
"""render_es4_manifests.py — generate k8s/es4/services/*.yaml from the PRODUCTION slices.

Run from the repo root; commit the outputs (they are reviewed like any change).

WHY derive from production: the prod manifests carry every service-specific env
(health ports, source switches, per-topic envs). On es4 the runtime applies
TOPIC_PREFIX=es. to every topic — including env-supplied values
(KafkaSettings.topicValue -> RuntimeProfileConfig.topic prefixes both defaults and
env overrides) — so the prod env carries over UNCHANGED and every topic lands
es.-prefixed. Environment-level knobs come from the es4-common-env ConfigMap +
es4-runtime-secrets Secret referenced here instead of the prod ones.

Transforms per manifest:
  1. envFrom: options-edge-config -> es4-common-env; options-edge-runtime-secrets ->
     es4-runtime-secrets; every other envFrom entry dropped (all optional in prod).
  2. image -> 192.168.100.252:5000/<basename>:dev (digest-pinned by the es4-deploy
     Jenkins job before every apply — never rolled out as a floating tag).
  3. per-service ES env appended (q=r for gex; multiplier 50 for strike-flow /
     delta-flow; gex OI fetch disabled — the OPRA/OSI symbology doesn't apply to GLBX).
"""

import copy
import io
import os
import sys

import yaml

REGISTRY = "192.168.100.252:5000"
OUT_DIR = "k8s/es4/services"

# es4 core set (Gate-2 v1 scope; hpsf/replay/unified-sr descoped; mission-pace/pressure
# have no standalone slices yet — follow-up; ibkr/raw-postgres-writer out of the ES path).
SERVICES = [
    "databento-gex", "databento-gex-history", "databento-maxpain", "databento-mission-sandwich",
    "databento-volume-aggregator", "dealer-ledger", "dealer-ledger-calibration", "delta-flow",
    "directional-pressure", "gex-delta-redis-writer", "option-price-behavior", "pin-postgres-writer",
    "pressure-postgres-writer", "raw-to-display", "strike-flow-avro-adapter", "strike-flow-classifier",
    "strike-liquidity-heatmap", "volume-pace",
]

ES_ENV = {
    "databento-gex": [
        {"name": "DATABENTO_GEX_RISK_FREE_RATE", "value": "0.04"},
        {"name": "DATABENTO_GEX_DIVIDEND_YIELD", "value": "0.04"},   # q=r -> Black-76 on the future
        {"name": "DATABENTO_GEX_OI_DIRECT_FETCH_ENABLED", "value": "false"},
        {"name": "DATABENTO_GEX_OI_BASELINE_BACKFILL_ENABLED", "value": "false"},
    ],
    "strike-flow-classifier": [
        {"name": "STRIKE_FLOW_CONTRACT_MULTIPLIER", "value": "50"},
    ],
    "delta-flow": [
        {"name": "DELTA_FLOW_DEFAULT_CONTRACT_MULTIPLIER", "value": "50"},
        {"name": "DELTA_FLOW_VERIFIED_MULTIPLIERS", "value": "ES:50"},
    ],
    # ES underlying is the mirrored future-trades topic (es.underlying.es.trades after prefix),
    # not the SPX cash-price topic (Codex finding #3, 2026-07-12).
    "option-price-behavior": [
        {"name": "OPTION_PRICE_BEHAVIOR_INPUT_UNDERLYING_TOPIC", "value": "underlying.es.trades", "_override": True},
    ],
}

# IBKR-variant workloads have no place in the ES pipeline (Codex finding #5).
DROP_WORKLOADS = {"raw-to-display-service", "directional-pressure-service"}

HEADER = """\
# GENERATED by scripts/es4/render_es4_manifests.py from {src} — DO NOT EDIT BY HAND.
# es4 environment: env-level knobs come from es4-common-env / es4-runtime-secrets;
# every topic gets the es. prefix at runtime via TOPIC_PREFIX (incl. env-supplied values).
# Deploy ONLY via Jenkinsfile.es4-deploy (digest-pins the :dev tag before apply).
"""


def transform_env_from(env_from):
    out = []
    for ref in env_from or []:
        cm = ref.get("configMapRef", {}).get("name")
        sec = ref.get("secretRef", {}).get("name")
        if cm == "options-edge-config":
            out.append({"configMapRef": {"name": "es4-common-env"}})
        elif sec == "options-edge-runtime-secrets":
            out.append({"secretRef": {"name": "es4-runtime-secrets"}})
        # everything else (feed-env etc., all optional in prod) is intentionally dropped
    if not any(r.get("configMapRef", {}).get("name") == "es4-common-env" for r in out):
        out.insert(0, {"configMapRef": {"name": "es4-common-env"}})
    return out


def transform(svc, docs):
    # drop IBKR-variant Deployments/Services wholesale
    docs = [d for d in docs
            if not (isinstance(d, dict) and d.get("kind") in ("Deployment", "Service")
                    and d.get("metadata", {}).get("name") in DROP_WORKLOADS)]
    claim_names = []
    for doc in docs:
        if not isinstance(doc, dict) or doc.get("kind") != "Deployment":
            continue
        for v in (doc["spec"]["template"]["spec"].get("volumes") or []):
            pvc = v.get("persistentVolumeClaim", {}).get("claimName")
            if pvc:
                claim_names.append(pvc)
        for c in doc["spec"]["template"]["spec"]["containers"]:
            c["envFrom"] = transform_env_from(c.get("envFrom"))
            # redis runs in the es4 compose stack on the HOST, not in-cluster
            for e in c.get("env") or []:
                if e.get("value") == "options-edge-redis":
                    e["value"] = "192.168.100.4"
            base = c["image"].split("/")[-1].split(":")[0]
            c["image"] = f"{REGISTRY}/{base}:dev"
            c.pop("imagePullPolicy", None)
            extra = ES_ENV.get(svc, [])
            if extra:
                env = c.get("env") or []
                by_name = {e["name"]: e for e in env}
                for item in copy.deepcopy(extra):
                    override = item.pop("_override", False)
                    if item["name"] in by_name:
                        if override:
                            by_name[item["name"]]["value"] = item["value"]
                    else:
                        env.append(item)
                c["env"] = env
    # emit a PVC for every claim referenced (fresh cluster has none; k3s default
    # local-path StorageClass provisions on first bind — Codex blocker #1)
    for name in sorted(set(claim_names)):
        docs.append({
            "apiVersion": "v1", "kind": "PersistentVolumeClaim",
            "metadata": {"name": name, "namespace": "options-edge",
                         "labels": {"app.kubernetes.io/part-of": "options-edge-es4"}},
            "spec": {"accessModes": ["ReadWriteOnce"],
                     "resources": {"requests": {"storage": "5Gi"}}},
        })
    return docs


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    for svc in SERVICES:
        src = f"k8s/services/{svc}/overlays/production/manifest.yaml"
        if not os.path.isfile(src):
            sys.exit(f"MISSING slice: {src}")
        with open(src) as f:
            docs = [d for d in yaml.safe_load_all(f) if d is not None]
        docs = transform(svc, docs)
        buf = io.StringIO()
        yaml.safe_dump_all(docs, buf, sort_keys=False, default_flow_style=False)
        with open(f"{OUT_DIR}/{svc}.yaml", "w") as f:
            f.write(HEADER.format(src=src))
            f.write(buf.getvalue())
        print(f"rendered {OUT_DIR}/{svc}.yaml")
    print(f"done: {len(SERVICES)} services")


if __name__ == "__main__":
    main()
