#!/usr/bin/env bash
# SERVICE-SLICE GENERATOR (standalone-service-deployment — processing full split).
#
# For every services.yaml entry with `sliceGenerated: true`, extracts the service's own
# workload docs (its Deployments + Services, by metadata.name) from the MONOLITHIC env
# overlay render and writes them as the standalone overlay:
#     k8s/services/<name>/overlays/<env>/{manifest.yaml,kustomization.yaml}
#
# Because the slice IS the monolith's render of that service, the mirror rule
# (scripts/ci/validate-services.sh) holds by construction. When the monolith changes a
# service (new env var, image, patch), re-run this script and commit the regenerated
# slices — CI fails on drift until you do.
#
# Hand-authored slices (web) are NOT touched: only sliceGenerated services regenerate.
set -euo pipefail
cd "$(dirname "$0")/../.."
command -v yq >/dev/null 2>&1 || { echo "FATAL: yq is required" >&2; exit 1; }

ENVS=(dev production experiment)
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT

for e in "${ENVS[@]}"; do
  kubectl kustomize "k8s/overlays/$e" >"$TMP/mono-$e.yaml"
done

count=0
while IFS= read -r name; do
  deployments="$(yq -r ".services[] | select(.name == \"$name\") | .deployments[]" services.yaml)"
  for e in "${ENVS[@]}"; do
    # skip envs where the service does not render (e.g. experiment excludes some)
    docs="$TMP/svc.yaml"; : >"$docs"
    for dep in $deployments; do
      # separator between appended documents (yq emits none across invocations)
      [ -s "$docs" ] && echo "---" >>"$docs"
      yq "select((.kind == \"Deployment\" or .kind == \"Service\") and .metadata.name == \"$dep\")" \
        "$TMP/mono-$e.yaml" >>"$docs"
    done
    if ! grep -q '^kind:' "$docs"; then
      rm -rf "k8s/services/$name/overlays/$e"
      continue
    fi
    dir="k8s/services/$name/overlays/$e"
    mkdir -p "$dir"
    {
      echo "# GENERATED by scripts/deploy/generate-service-slices.sh — DO NOT EDIT BY HAND."
      echo "# This is the monolithic k8s/overlays/$e render of ONLY this service's workload"
      echo "# (mirror rule holds by construction). To change the service, change the base"
      echo "# manifests/overlay patches and re-run the generator."
      echo "#"
      echo "# DEPLOYMENT SAFETY — NEVER kubectl-apply this manifest directly. It is a"
      echo "# PRE-DIGEST render: the image ref below is at best a mutable TAG (and, where the"
      echo "# overlay carries no env mapping, the BASE dev-registry ref — not this env's image)."
      echo "# The ONLY deploy paths are the Jenkins jobs (Jenkinsfile.service-deploy ->"
      echo "# scripts/deploy/service-deploy.sh, or the monolithic Jenkinsfile), which remap the"
      echo "# image via image-tags/$e.yaml and digest-pin it fail-closed BEFORE any apply."
      echo "# Applying this file directly bypasses that pinning and can roll out a wrong or"
      echo "# stale image."
      cat "$docs"
    } >"$dir/manifest.yaml"
    cat >"$dir/kustomization.yaml" <<EOF
# GENERATED — see manifest.yaml header.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifest.yaml
EOF
  done
  count=$((count + 1))
done < <(yq -r '.services[] | select(.sliceGenerated == true) | .name' services.yaml)

echo "generated slices for $count services (envs: ${ENVS[*]})"
