#!/usr/bin/env bash
# ES4 RENDER DRIFT GATE.
#
# k8s/es4/services/*.yaml are GENERATED by scripts/es4/render_es4_manifests.py from the
# PRODUCTION slices and say "DO NOT EDIT BY HAND". Nothing enforced that. This does: it runs the
# renderer and fails if the committed output differs, i.e. the author must commit the regenerated
# manifests. Same shape as the "Service slices are regenerated (no drift)" step that guards
# k8s/services/** (see .github/workflows/deploy-validation.yml).
#
# WHY it is worth a gate. Drift here is silent and it points at a LIVE environment. es4 renders
# from the production slices, so any prod change lands in the es4 output — but only when someone
# next re-runs the renderer, which they do for an unrelated reason, in a large diff, weeks later.
# Two ways that goes wrong, both observed on main and both fixed in the commit that added this:
#
#   1. INHERITED FLIP. prod retired the OI nowcast (#783) and flipped
#      DATABENTO_GEX_DYNAMIC_OI_ENABLED to "false". es4's committed manifest still said "true"
#      (itself inherited from prod, never an es4 decision), so the next unrelated re-render would
#      have carried a behaviour change into es4 inside somebody else's diff.
#   2. INHERITED WIRING. prod armed the pre-open IBKR GEX path; those five IBKR_GEX_* envs were
#      queued to render onto es4, where the publish target is the es4 primary GEX topic. See
#      DROP_ENV_PREFIXES in the renderer.
#
# The gate does not decide which side is right — it makes the difference impossible to merge
# without someone looking at it. That is the whole point.
#
# Requires: python3 with PyYAML. Read-only; no cluster access needed.
set -euo pipefail
cd "$(dirname "$0")/../.."

python3 -c 'import yaml' 2>/dev/null || {
  echo "FATAL: PyYAML is required (python3 -m pip install pyyaml)" >&2; exit 1; }

echo "=== rendering es4 manifests ==="
# The renderer's own fail-closed asserts (assert_no_silent_prod_wins,
# assert_drop_prefixes_are_coherent) run here too, so a bad ES_ENV/DROP_ENV_PREFIXES edit fails
# at this line rather than showing up as a confusing diff below.
python3 scripts/es4/render_es4_manifests.py

if ! git diff --quiet -- k8s/es4/services; then
  echo "FAIL: k8s/es4/services is out of date with scripts/es4/render_es4_manifests.py." >&2
  echo "      These files are GENERATED. Do not hand-edit them: express the es4 intent in the" >&2
  echo "      renderer (ES_ENV / DROP_ENV_PREFIXES / ES4_KEEP_DOWN), then run" >&2
  echo "      'python3 scripts/es4/render_es4_manifests.py' and commit the result." >&2
  echo "      A comment added to a generated file cannot survive at all — PyYAML does not emit" >&2
  echo "      comments, so the note belongs next to its ES_ENV entry in the renderer." >&2
  echo "" >&2
  git --no-pager diff --stat -- k8s/es4/services >&2
  echo "----- full diff -----" >&2
  git --no-pager diff -- k8s/es4/services >&2
  exit 1
fi

echo "=== validate-es4-render: OK (committed manifests match the renderer) ==="
