#!/usr/bin/env bash
# ES4 RENDER DRIFT GATE.
#
# k8s/es4/services/*.yaml are GENERATED by scripts/es4/render_es4_manifests.py from the
# PRODUCTION slices and say "DO NOT EDIT BY HAND". Nothing enforced that. This does, in two
# directions:
#
#   A. CONTENT — the renderer's output must equal what is committed.
#   B. FILE SET — every .yaml in k8s/es4/services must be accounted for: either the renderer
#      produces it, or it is a declared hand-authored es4-only manifest. Nothing else.
#
# (A) alone is a weak gate, because `git diff` says nothing about a file the renderer never
# writes. Jenkinsfile.es4-deploy's deploy-all does `ls k8s/es4/services/*.yaml`, so ANY file in
# this directory is applied to the live es4 cluster — including one the generator has stopped
# producing, or one that was never committed at all. (B) is what makes the directory itself the
# unit of review.
#
# WHY it is worth a gate. Drift here is silent and it points at a LIVE environment. es4 renders
# from the production slices, so any prod change lands in the es4 output — but only when someone
# next re-runs the renderer, which they do for an unrelated reason, in a large diff, weeks later.
# Three ways that goes wrong, all three found on main when this gate was written:
#
#   1. INHERITED FLIP. prod retired the OI nowcast (#783) and flipped
#      DATABENTO_GEX_DYNAMIC_OI_ENABLED to "false". es4's committed manifest still said "true"
#      (itself inherited from prod, never an es4 decision), so the next unrelated re-render would
#      have carried a behaviour change into es4 inside somebody else's diff.
#   2. INHERITED WIRING. prod armed the pre-open IBKR GEX path; those five IBKR_GEX_* envs were
#      queued to render onto es4, where the publish target is the es4 primary GEX topic. See
#      DROP_ENV_PREFIXES in the renderer.
#   3. FELL OUT OF THE RENDER. c12e87c meant to drop greek-move-authenticity from SERVICES and
#      deleted the whole source line, taking strike-intelligence and vix-option-inteligence with
#      it. Their manifests still say "GENERATED", deploy-all still applies them, and the renderer
#      has not produced them since. Only check (B) sees this class.
#
# Precisely on (3): this gate catches a NEW dropout, and QUARANTINES the two existing ones in
# KNOWN_STALE rather than failing on them — see that list for why re-rendering them is a
# behaviour change and not a regeneration. "Must only shrink" is a review rule, not an enforced
# one: adding a name to KNOWN_STALE will pass CI, so treat any growth of that list as the change
# under review rather than as housekeeping.
#
# The gate does not decide which side is right — it makes the difference impossible to merge
# without someone looking at it. That is the whole point.
#
# NOT read-only: it RUNS the renderer, so it rewrites k8s/es4/services/*.yaml in place. On a
# clean checkout that is a no-op; locally, regenerated output is exactly what you need to commit.
# Requires: python3 with PyYAML, git.
set -euo pipefail
cd "$(dirname "$0")/../.."

# The version the committed manifests were rendered with. The check compares emitted YAML
# byte-for-byte, so a serialization change between PyYAML releases reads as drift. CI installs
# this exact version (.github/workflows/deploy-validation.yml); locally we only warn, because a
# mismatch is a reproducibility problem rather than a repo defect.
PINNED_PYYAML="6.0.3"

python3 -c 'import yaml' 2>/dev/null || {
  echo "FATAL: PyYAML is required (python3 -m pip install 'pyyaml==$PINNED_PYYAML')" >&2; exit 1; }
have="$(python3 -c 'import yaml; print(yaml.__version__)')"
if [ "$have" != "$PINNED_PYYAML" ]; then
  echo "WARNING: PyYAML $have != pinned $PINNED_PYYAML. Emitted YAML may differ purely by" >&2
  echo "         formatting; if this reports drift you cannot explain, match the pin first." >&2
fi

echo "=== A) rendering es4 manifests ==="
# The renderer's own fail-closed asserts (assert_no_silent_prod_wins,
# assert_drop_prefixes_are_coherent) run here too, so a bad ES_ENV/DROP_ENV_PREFIXES edit fails
# at this line rather than showing up as a confusing diff below.
python3 scripts/es4/render_es4_manifests.py

# Compare against HEAD, not the index: the question is whether the COMMIT is consistent with the
# renderer. Plain `git diff` would compare against staged content and call a staged-but-uncommitted
# fix "clean". --porcelain additionally reports UNTRACKED files, which no `git diff` form does.
dirty="$(git status --porcelain -- k8s/es4/services)"
if [ -n "$dirty" ]; then
  echo "FAIL: k8s/es4/services is out of date with scripts/es4/render_es4_manifests.py." >&2
  echo "      These files are GENERATED. Do not hand-edit them: express the es4 intent in the" >&2
  echo "      renderer (ES_ENV / DROP_ENV_PREFIXES / ES4_KEEP_DOWN), then run" >&2
  echo "      'python3 scripts/es4/render_es4_manifests.py' and commit the result." >&2
  echo "      A comment added to a generated file cannot survive at all — PyYAML does not emit" >&2
  echo "      comments, so the note belongs next to its ES_ENV entry in the renderer." >&2
  echo "" >&2
  printf '%s\n' "$dirty" >&2
  echo "----- full diff vs HEAD -----" >&2
  git --no-pager diff HEAD -- k8s/es4/services >&2
  exit 1
fi
echo "ok: committed manifests match the renderer"

echo "=== B) every manifest in k8s/es4/services is accounted for ==="
python3 - <<'PY'
import importlib.util, os, sys

OUT_DIR = "k8s/es4/services"

# SERVICES comes from the renderer itself — one source of truth for what IS generated.
# Importing under a non-__main__ name does not run main().
spec = importlib.util.spec_from_file_location("es4r", "scripts/es4/render_es4_manifests.py")
r = importlib.util.module_from_spec(spec)
spec.loader.exec_module(r)
rendered = set(r.SERVICES)

# Hand-authored es4-ONLY manifests: no production slice exists to render them from, and they
# carry their own explanatory headers rather than the GENERATED banner. Legitimately outside
# the renderer; still deployed by deploy-all, so they are declared here rather than tolerated.
HAND_AUTHORED = {
    "es-feed",            # ES-0DTE Databento feed; owns a live session, excluded from deploy-all
    "es-feed-gateway",    # prod feed-gateway binary, env-only divergence
    "es-web",             # prod web binary, env-only divergence
    "es-aggressor-flow",  # ES-only continuous futures aggressor analysis
}

# KNOWN STALE — generated files the renderer no longer produces. c12e87c removed
# greek-move-authenticity from SERVICES by deleting the whole source line, silently taking these
# two with it; greek-move-authenticity was restored in b5cb746 (#705) and these were not. They
# still claim "GENERATED", and deploy-all still applies them, so what is live on es4 is a
# 2026-07 render frozen mid-flight.
#
# Deliberately NOT fixed by simply re-adding them to SERVICES: that is a behaviour change needing
# its own per-env authority review, not a regeneration. Re-rendering strike-intelligence today
# would DROP STRIKE_INTEL_ACTION_MIN_TOTAL_PREMIUM=100000 — an es4-only premium floor (§7c,
# processing #371) that lives ONLY in the generated file and would have to move into ES_ENV first
# — and would pull in nine SPX-tuned knobs; vix-option-inteligence would take a 100m -> 500m CPU
# request bump on a box whose capacity pressure is why ES4_KEEP_DOWN exists.
#
# This list must only ever SHRINK. Emptying it is the fix.
KNOWN_STALE = {
    "strike-intelligence",
    "vix-option-inteligence",
}

# REGULAR files only, and no symlinks. Classifying on filename alone would let a committed
# symlink or a directory named "<something>.yaml" inherit an allowlisted name.
#
# On a RENDERED path the renderer refuses to write at all (open(...,"w") follows a symlink, so
# it would otherwise overwrite the target while this directory still looked clean) — that guard
# is in render_es4_manifests.py because it has to fire BEFORE the write, and this script renders
# first. What is left for here is the HAND_AUTHORED and unaccounted paths, which the renderer
# never touches and so never inspects.
on_disk, irregular = set(), []
for f in sorted(os.listdir(OUT_DIR)):
    if not f.endswith(".yaml"):
        continue
    p = os.path.join(OUT_DIR, f)
    if os.path.islink(p) or not os.path.isfile(p):
        irregular.append(f)
    else:
        on_disk.add(f[:-5])

accounted = rendered | HAND_AUTHORED | KNOWN_STALE
fail = False

if irregular:
    fail = True
    print(f"FAIL: {OUT_DIR} holds non-regular .yaml entries (symlink or directory): "
          f"{', '.join(irregular)}", file=sys.stderr)
    print("      Every deployable path here must be a plain committed file.", file=sys.stderr)

unaccounted = sorted(on_disk - accounted)
if unaccounted:
    fail = True
    print(f"FAIL: {OUT_DIR} holds manifest(s) the renderer does not produce and that are not "
          f"declared hand-authored:", file=sys.stderr)
    for n in unaccounted:
        print(f"  {n}.yaml", file=sys.stderr)
    print("      deploy-all applies every file in this directory to the live es4 cluster.",
          file=sys.stderr)
    print("      Add the service to SERVICES, declare it in HAND_AUTHORED here, or delete it.",
          file=sys.stderr)

missing = sorted(rendered - on_disk)
if missing:
    fail = True
    print(f"FAIL: SERVICES lists service(s) with no manifest in {OUT_DIR}: "
          f"{', '.join(missing)}", file=sys.stderr)

# A declared-stale entry that is gone, or that came back into SERVICES, means the list is lying.
for n in sorted(KNOWN_STALE):
    if n in rendered:
        fail = True
        print(f"FAIL: {n} is in SERVICES and in KNOWN_STALE. It is rendered again — drop it "
              f"from KNOWN_STALE.", file=sys.stderr)
    elif n not in on_disk:
        fail = True
        print(f"FAIL: {n} is in KNOWN_STALE but has no manifest. Drop it from KNOWN_STALE.",
              file=sys.stderr)

for n in sorted(HAND_AUTHORED & rendered):
    fail = True
    print(f"FAIL: {n} is both rendered by SERVICES and declared HAND_AUTHORED. Pick one.",
          file=sys.stderr)

# PRESENCE, not just permission. Without this the allowlist is one-directional: a committed
# deletion of es-web.yaml leaves the worktree clean, so check A sees nothing, and check B would
# happily report "4 hand-authored" while counting files that are gone. These are deploy-all
# inputs; losing one silently is the same class of miss as gaining one.
for n in sorted(HAND_AUTHORED - on_disk):
    fail = True
    print(f"FAIL: {n} is declared HAND_AUTHORED but has no manifest in {OUT_DIR}. If it was "
          f"removed on purpose, drop it from HAND_AUTHORED.", file=sys.stderr)

if fail:
    sys.exit(1)

print(f"ok: {len(on_disk)} manifest(s) = {len(rendered)} rendered "
      f"+ {len(HAND_AUTHORED)} hand-authored + {len(KNOWN_STALE)} known-stale")
if KNOWN_STALE:
    # Printed on EVERY green run on purpose: this is unfinished business on a live environment,
    # and a quarantine nobody sees again is just a silence with extra steps.
    print("NOTE: still un-rendered and still deployed by deploy-all: "
          + ", ".join(sorted(KNOWN_STALE)))
PY

echo "=== validate-es4-render: OK ==="
