apiVersion: v1
kind: Service
metadata:
  name: es-trade-linearizer-service
  namespace: options-edge
  labels:
    app.kubernetes.io/name: es-trade-linearizer-service
    app.kubernetes.io/component: es-trade-linearizer-service
    app.kubernetes.io/part-of: options-edge
spec:
  selector:
    app.kubernetes.io/name: es-trade-linearizer-service
  ports:
    - name: health
      port: 8152
      targetPort: health
