events {}
http {
  map $http_upgrade $connection_upgrade { default upgrade; "" close; }
  server {
    listen 8098;
    server_name _;
    location = /ws/events {
      proxy_pass http://host.docker.internal:8091/ws/events;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
    }
    location / {
      proxy_pass http://host.docker.internal:8090;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-Host $host;
      sub_filter_once off;
      sub_filter_types text/html text/css application/javascript application/json;
      sub_filter 'ws://localhost:8091/ws/events' 'wss://dev.bleadingoptions.com/ws/events';
      sub_filter 'http://192.168.100.102:8089/' 'https://dev-auth.bleadingoptions.com/';
    }
  }
}
