apiVersion: v1
kind: ConfigMap
metadata:
  name: options-edge-config
  namespace: options-edge
data:
  APP_MARKET_DATA_SOURCE: DATABENTO
  APP_FEED_GATEWAY_ENABLED: "true"
  KAFKA_BOOTSTRAP_SERVERS: kafka-0:9092,kafka-1:9092
  KAFKA_BROKER_COUNT: "2"
  KAFKA_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TOPIC_RETENTION_MS: "86400000"
  KAFKA_TOPIC_CLEANUP_POLICY: delete
  KAFKA_TOPIC_PARTITIONS_DEFAULT: "32"
  KAFKA_CONTROL_TOPIC_PARTITIONS: "1"
