apiVersion: v1
kind: Service
metadata:
  name: delta-flow-service
  namespace: options-edge
  labels:
    app.kubernetes.io/name: delta-flow-service
    app.kubernetes.io/component: delta-flow-service
    app.kubernetes.io/part-of: options-edge
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: delta-flow-service
  ports:
    - name: health
      port: 8110
      targetPort: health
