apiVersion: v1
kind: Service
metadata:
  name: es-open-direction-postgres-writer
  namespace: options-edge
  labels:
    app.kubernetes.io/name: es-open-direction-postgres-writer
    app.kubernetes.io/component: es-open-direction-postgres-writer
    app.kubernetes.io/part-of: options-edge
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: es-open-direction-postgres-writer
  ports:
    - name: health
      port: 8080
      targetPort: health
