apiVersion: v1
kind: Service
metadata:
  name: feed-gateway-service
  namespace: options-edge
  labels:
    app.kubernetes.io/name: feed-gateway-service
    app.kubernetes.io/part-of: options-edge
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8091"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: feed-gateway-service
  ports:
    - name: http
      port: 8091
      targetPort: http
