apiVersion: v1
kind: Service
metadata:
  name: hpsf-postgres-writer-service
  namespace: options-edge
  labels:
    app.kubernetes.io/name: hpsf-postgres-writer-service
    app.kubernetes.io/component: hpsf-postgres-writer
    app.kubernetes.io/part-of: options-edge
spec:
  selector:
    app.kubernetes.io/name: hpsf-postgres-writer-service
  ports:
    - name: http
      port: 8080
      targetPort: http
