apiVersion: v1
kind: Service
metadata:
  name: options-edge-integration-test
  namespace: options-edge
  labels:
    app.kubernetes.io/name: options-edge-integration-test
    app.kubernetes.io/part-of: options-edge
spec:
  selector:
    app.kubernetes.io/name: options-edge-integration-test
  ports:
    - name: http
      port: 8080
      targetPort: http
