apiVersion: v1
kind: Service
metadata:
  name: invasion-postgres-writer
  namespace: options-edge
  labels:
    app.kubernetes.io/name: invasion-postgres-writer
    app.kubernetes.io/component: invasion-postgres-writer
    app.kubernetes.io/part-of: options-edge
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: invasion-postgres-writer
  ports:
    - name: health
      port: 8121
      targetPort: health
