resources:
  - namespace.yaml
  - configmap.yaml
  - ibkr-feed-deployment.yaml
  - ibkr-feed-service.yaml
  - feed-gateway-deployment.yaml
  - feed-gateway-service.yaml
  - directional-pressure-deployment.yaml
  - directional-pressure-service.yaml
  - integration-test-deployment.yaml
  - integration-test-service.yaml
  - pressure-postgres-writer-deployment.yaml
  - pressure-postgres-writer-service.yaml
  - raw-to-display-deployment.yaml
  - raw-to-display-service.yaml
  - raw-postgres-writer-deployment.yaml
  - raw-postgres-writer-service.yaml
  - volume-pace-deployment.yaml
  - volume-pace-service.yaml
  - volume-sandwich-deployment.yaml
  - volume-sandwich-service.yaml
  - unusual-whales-gex-deployment.yaml
  - unusual-whales-gex-service.yaml
