apiVersion: v1
kind: Service
metadata:
  name: option-truth-engine-service
  namespace: options-edge
  labels:
    app.kubernetes.io/name: option-truth-engine-service
    app.kubernetes.io/component: option-truth-engine-service
    app.kubernetes.io/part-of: options-edge
spec:
  selector:
    app.kubernetes.io/name: option-truth-engine-service
  ports:
    - name: health
      port: 8131
      targetPort: health
