apiVersion: v1
kind: Service
metadata:
  name: raw-postgres-writer
  namespace: options-edge
  labels:
    app.kubernetes.io/name: raw-postgres-writer
    app.kubernetes.io/part-of: options-edge
spec:
  selector:
    app.kubernetes.io/name: raw-postgres-writer
  ports:
    - name: health
      port: 8080
      targetPort: health
