apiVersion: v1
kind: Service
metadata:
  name: es-aggressor-flow-service
  namespace: options-edge
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /metrics
    prometheus.io/port: '8151'
  labels:
    app.kubernetes.io/name: es-aggressor-flow-service
    app.kubernetes.io/part-of: options-edge
spec:
  selector:
    app.kubernetes.io/name: es-aggressor-flow-service
  ports:
    - name: health
      port: 8151
      targetPort: health
