import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.optionsedge.contracts.volpremium.CalendarArtifact;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * The JAVA side of the calendar parity vectors: for every vectors/NAME.json, what the REAL contract does with
 * those bytes, through exactly the reader the engine and the publisher use (ArtifactBinding.JSON — an
 * ObjectMapper with JavaTimeModule and WRITE_DATES_AS_TIMESTAMPS disabled — into CalendarArtifact, whose
 * constructor validates and re-hashes; then requireWithinWire on the bytes, as LedgerPublisher.validateCalendar
 * does). Prints one line per vector: NAME<TAB>OK<TAB>hash or NAME<TAB>REJECT<TAB>reason. regenerate-expected.sh
 * writes that to expected.tsv; scripts/ci/validate-vol-premium-calendar.sh --vectors holds its Python port to it.
 *
 * NOTHING is published or written by this program.
 */
public final class CalendarVectors {
    static final ObjectMapper JSON = new ObjectMapper()
            .registerModule(new JavaTimeModule())
            .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);

    public static void main(String[] args) throws Exception {
        Path dir = Path.of(args[0]);
        List<Path> files = new ArrayList<>();
        try (var s = Files.list(dir)) {
            s.filter(p -> p.toString().endsWith(".json")).sorted().forEach(files::add);
        }
        StringBuilder out = new StringBuilder();
        out.append("# GENERATED by regenerate-expected.sh from CalendarVectors.java against the real contract classes.\n");
        out.append("# name\tverdict\thash (OK) or exception: message (REJECT)\n");
        for (Path p : files) {
            String name = p.getFileName().toString().replaceAll("\\.json$", "");
            byte[] bytes = Files.readAllBytes(p);
            String verdict;
            try {
                CalendarArtifact.requireWithinWire(bytes);
                String json = new String(bytes, StandardCharsets.UTF_8);
                CalendarArtifact c = JSON.readValue(json, CalendarArtifact.class);
                String computed = CalendarArtifact.computeContentHash(c.calendarVersion(), c.validFromDate(),
                        c.validThroughDate(), c.entries());
                if (!computed.equals(c.calendarContentHash())) {
                    throw new IllegalStateException("CALENDAR_HASH_MISMATCH: declares " + c.calendarContentHash()
                            + " but hashes to " + computed);
                }
                verdict = "OK\t" + computed;
            } catch (Throwable t) {
                String m = String.valueOf(t.getMessage()).split("\\R", 2)[0];
                if (m.length() > 160) {
                    m = m.substring(0, 160) + "…";
                }
                verdict = "REJECT\t" + t.getClass().getSimpleName() + ": " + m;
            }
            out.append(name).append('\t').append(verdict).append('\n');
        }
        System.out.print(out);
    }
}
