apiVersion: apps/v1
kind: Deployment
metadata:
  name: databento-volume-aggregator
  namespace: options-edge
spec:
  template:
    spec:
      containers:
        - name: databento-volume-aggregator
          env:
            - name: KAFKA_DATABENTO_VOLUME_AGGREGATOR_PROCESSING_GUARANTEE
              value: at_least_once
